version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: vue_lib_web
    privileged: true
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - db
    ports:
      - 1111:80

  db:
    image: mysql:5.7
    container_name: vue_lib_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    ports:
      - 1112:3306

volumes:
  mysql_data:
    driver: local
